spring:
  datasource:
    username: root
    password: nishengri
    url: jdbc:mysql://localhost:3306/gokproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver